apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secure-messenger

resources:
- namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- web-deployment.yaml
- web-service.yaml
- ingress.yaml
- hpa.yaml
- rbac.yaml

commonLabels:
  app: secure-messenger
  managed-by: kustomize
