apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-messenger
  labels:
    app: secure-messenger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-messenger
  labels:
    app: secure-messenger
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-messenger
  labels:
    app: secure-messenger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secure-messenger
subjects:
- kind: ServiceAccount
  name: secure-messenger
